import Head from 'next/head';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Welcome to ALX Project 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to ALX Project 2</h1>
      </main>
    </div>
  );
};

export default Home;